version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vps-backend
    environment:
      - PORT=3000
      - JWT_SECRET=supersecret
    volumes:
      - ./server:/app
    ports:
      - "18876:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vps-frontend
    depends_on:
      - backend
    ports:
      - "18877:80" 